AddLocationForm:
<AddLocationForm@BoxLayout>:
    orientation:"vertical"
    BoxLayout:
        height:"40dp"
        size_hint_y:None
        TextInput:
           size_hint_x:50
        Button:
            text:"Search"
            size_hint_x:25
        Button:
            text:"Current Location"
            size_hint_x:25
    ListView:
        item_strings:["Kanpur,Uttar Pradesh","Kanpur,India"]
